import fs from "node:fs"
import { getAttackByPosition, attackLineColors, attackTypeLabels, type PositionAttackGroup, type Play } from "./lib/attack/volley-stats.ts"
const positions = ["ponta","meio","oposto","fundo1"] as const
const types = ["diagonal_maior","diagonal_menor","paralela","paragonal","pingo"] as const
const plays: Play[] = []
let id=1
for(let i=0;i<50;i++){ plays.push({ id:id++, team:"A", status:"levantamento", position: positions[i%positions.length] as any, attackType: types[i%types.length] as any, result:"ponto", timestamp:new Date() }) }
const logoBuf = fs.readFileSync("public/volley-tech-logo.png")
const logoSrc = "data:image/png;base64,"+logoBuf.toString("base64")
const courtSvg = (group: PositionAttackGroup) => {
  const lines = group.lines.map((l)=>{ const color=attackLineColors[l.attackType]??"#f97316"; const midX=(l.line.startX+l.line.endX)/2; const midY=(l.line.startY+20+l.line.endY)/2; const w=Math.max(2.5,l.percentage/9); return `<line x1="${l.line.startX}" y1="${l.line.startY+20}" x2="${l.line.endX}" y2="${l.line.endY}" stroke="${color}" stroke-width="${w}" stroke-linecap="round" opacity="0.9" /><circle cx="${midX}" cy="${midY}" r="11" fill="${color}" /><text x="${midX}" y="${midY+3.5}" text-anchor="middle" font-size="9" fill="#fff" font-weight="bold">${l.percentage}%</text>` }).join("")
  const legend = group.lines.map((l)=>`<span style="display:inline-flex;align-items:center;gap:4px;background:#f1f5f9;padding:2px 6px;border-radius:6px;font-size:10px;margin:2px"><span style="width:8px;height:8px;border-radius:50%;background:${attackLineColors[l.attackType]??"#f97316"}"></span>${attackTypeLabels[l.attackType]??l.attackType}: <strong>${l.count} (${l.percentage}%)</strong></span>`).join("")
  return `<div style="border:1px solid #e2e8f0;border-radius:10px;padding:10px;background:#fff;break-inside:avoid"><div style="display:flex;justify-content:space-between;align-items:baseline;margin-bottom:6px"><strong style="color:#1e293b;font-size:13px">${group.label} <span style="color:#94a3b8;font-weight:normal">(${group.description})</span></strong><span style="font-size:11px;color:#f97316;font-weight:bold">${group.total} ataques</span></div><svg viewBox="0 0 200 220" width="190" height="209" preserveAspectRatio="xMidYMid meet" style="width:190px;height:209px;max-width:100%;display:block;margin:0 auto"><rect x="5" y="5" width="190" height="210" fill="#f5f0dc" stroke="#1e3a5f" stroke-width="3" rx="2" /><rect x="5" y="20" width="190" height="10" fill="#1e3a5f" /><text x="100" y="15" text-anchor="middle" font-size="9" fill="#1e3a5f" font-weight="bold">REDE</text><circle cx="20" cy="25" r="9" fill="#1e40af" /><text x="20" y="28.5" text-anchor="middle" font-size="8" fill="#fff" font-weight="bold">P2</text><circle cx="100" cy="25" r="9" fill="#1e40af" /><text x="100" y="28.5" text-anchor="middle" font-size="8" fill="#fff" font-weight="bold">P3</text><circle cx="180" cy="25" r="9" fill="#1e40af" /><text x="180" y="28.5" text-anchor="middle" font-size="8" fill="#fff" font-weight="bold">P4</text><line x1="5" y1="75" x2="195" y2="75" stroke="#1e3a5f" stroke-width="1.5" stroke-dasharray="8,4" /><circle cx="20" cy="190" r="6" fill="#94a3b8" opacity="0.5" /><text x="20" y="193" text-anchor="middle" font-size="7" fill="#1e3a5f" font-weight="bold">P5</text><circle cx="100" cy="190" r="6" fill="#94a3b8" opacity="0.5" /><text x="100" y="193" text-anchor="middle" font-size="7" fill="#1e3a5f" font-weight="bold">P6</text><circle cx="180" cy="190" r="6" fill="#94a3b8" opacity="0.5" /><text x="180" y="193" text-anchor="middle" font-size="7" fill="#1e3a5f" font-weight="bold">P1</text>${lines}</svg><div style="text-align:center;margin-top:6px">${legend}</div></div>`
}
const groups = getAttackByPosition(plays,"A")
const html = `<!DOCTYPE html><html><head><meta charset="UTF-8"><style>*{-webkit-print-color-adjust:exact;print-color-adjust:exact}body{font-family:Arial;padding:30px;max-width:900px;margin:0 auto}.courts-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}svg{break-inside:avoid}</style></head><body><div style="display:flex;align-items:center;gap:12px;border-bottom:2px solid #f97316;padding-bottom:10px"><img src="${logoSrc}" style="width:44px;height:44px;object-fit:contain"/><div><div style="font-size:11px;font-weight:bold;letter-spacing:2px;color:#f97316">VOLLEY TECH · ATTACK POSITION</div><h1 style="margin:2px 0 0">RELATÓRIO: Teste</h1></div></div><h2 style="color:#1e40af">Equipe A — Ataques por Local</h2><h3>Direções de Ataque por Local</h3><div class="courts-grid">${groups.map(courtSvg).join("")}</div></body></html>`
fs.writeFileSync("public/pdfcheck.html", html)
console.log("groups:", groups.length)
